[package]
edition = "2024"
license = "MIT"
name    = "zed_biome"
publish = false
version = "0.2.2"

[lib]
crate-type = ["cdylib"]
path       = "src/biome.rs"

[dependencies]
log                = "0.4.29"
tracing            = "0.1.44"
tracing-subscriber = "0.3.22"
zed_extension_api  = "0.7.0"
